version: "3"

services:
    mysql-docker-container:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=isc517practica3
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        ports:
            - 14000:14000
        volumes:
            - /data/mysql

    spring-boot-jpa-app:
        build: .
        depends_on:
            - mysql-docker-container
        ports:
            - 8080:8080
        volumes:
            - /data/spring-boot-app
